version: "3"
services:
  api:
      build: .
      container_name: fastapi
      depends_on:
        - postgres # spins up postgres before the api image is built. informs docker-compose that the postgres image is required before the api image is built.
      ports:
        - "8000:8000"
      volumes:
        - ./:/usr/src/app:ro   # mount the current directory to /usr/src/app allowing for source code change. the :ro means read only. it adds an extra layer of security ensuring that the docker container doesnt make changes to our code.
      command: uvicorn app.fast_orm:app --host 0.0.0.0 --port 8000 --reload # reloads api when code changes. when we use bind mount.

      environment:
        - DATABASE_HOSTNAME = postgres
        - DATABASE_PASSWORD = tomrules
        - DATABASE_PORT = 5432
        - DATABASE_NAME = fastapi database
        - DATABASE_USERNAME = postgres
        - SECRET_KEY = 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
        - ALGORITHM = HS256
        - ACCESS_TOKEN_EXPIRE_MINUTES = 30
  postgres:
      image: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=tomrules
        - POSTGRES_DB=fastapi database
      volumes:
        - ./postgres:/var/lib/postgresql/data # save the postgres data to the current directory so it doesn't get des
      ports:
        - "5432:5432"
volumes:
  postgres: